### ISSUE TITLE
Unsupported Realm file format version (11)

### ISSUE THREAD

**Issue by lor-enz** [eggheadgames/android-realm-asset-helper#14]
When trying to read a realm file in a blank android project following the description in the readme.md I get the following error 

Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/myapp/files/default.realm': Unsupported Realm file format version (11) 

I have the following questions:
I assume the (11) represents the version of the database file that I supply, correct?
Which database versions is the android-realm-asset-helper compatible with. Is my file too old or too new?

I'll be glad for any help :)

**Comment by mikemee** [comment]
Good question. I took a quick look but didn't see an answer. I think that it will depend on the version of Realm that you specific in your `build.gradle` file and the version of the database you created, so I suggest looking there first. Note that the Realm Studio will convert from an old format Realm file to a new one (or is it Realm Browser? Whichever one is newest!)

FYI, I just discovered a couple of days ago that current versions of Realm (as of a year or two ago even??) now have an option to provide an asset name and they will take care of copying.

I need to update the readme and mark this project as "inactive"!
