### ISSUE TITLE
Cannot resolve symbol `realmConfig`

### ISSUE THREAD

**Issue by Drag11** [eggheadgames/android-realm-asset-helper#5]
Doesn't compile, error:
Cannot resolve symbol `realmConfig`
Realm v 2.3.2

Looks like the code should look like that:
```
Realm.init(this);

        RealmAssetHelper.getInstance(this).loadDatabaseToStorage("data", "defaultpacked", new IRealmAssetHelperStorageListener() {
            @Override
            public void onLoadedToStorage(String realmDbName, RealmAssetHelperStatus status) {
                RealmConfiguration realmConfig = new RealmConfiguration.Builder()
                        .name(realmDbName)
                        .build();
                Realm realm = Realm.getInstance(realmConfig);
            }
        });
```

**Comment by mikemee** [comment]
@Drag11 thanks for the heads up. We haven't updated our Realm version in a while, so I'm guessing that's the problem. We'll take a look (most likely next week) and/or you can give us a PR to review. Thanks again!

@AlexDibrivnyy @yurii-diachenko Would you like to take a look at this and update as required?

**Comment by AlexDibrivnyy** [comment]
Hi @Drag11 , we checked all versions of Realm library and all of them works fine with `android-realm-asset-helper`.

Note, this (`android-realm-asset-helper`) library is only extension for Realm and you need to use it only when Realm is configured. 

If you still has problems with `Cannot resolve symbol realmConfig` or Realm configuration, then please try to add Realm using this tutorial https://realm.io/docs/java/latest/#getting-started

Thank you for you question and feel free to contact us. 

Best Regards,
Eggheadgames
